name: First Workflow
on: [push]
jobs:
    run-shell-commands:
      runs-on: ubuntu-latest
      steps:
        - name: echo a string
          run: echo "Hello GitHub Actions, this is my first workflow"
        - name: Multiline Command
          run: |
            node -v
            npm -v
